### PR TITLE
Refresh & update all the attributes, health check wait

### PR DESCRIPTION
**Pull request by rubbish**
This will catch the other `marathon_app` attributes to refresh and make sure that they get updated if they differ from the configuration vs marathon.

### CODE REVIEW

**Comment by rubbish** [comment]
I haven't yet ran this against env-setup, so I hasn't been tested fully against our stack.

**Comment by rubbish** [comment]
also https://github.com/gambol99/go-marathon/pull/71

**Comment by rubbish** [comment]
I also have a fix locally for https://github.com/gambol99/go-marathon/pull/72 when it gets merged in.

**Comment by rubbish** [comment]
tested against env-setup. I need to add `upgrade_strategy`s for all the apps that are missing it.

**Comment by sherzberg** [comment]
retest this please

**Comment by rubbish** [comment]
@sherzberg The marathon builds have been failing on jenkins for some time, but they've always passed locally. I chalk it up to the docker version mismatch between host and slave image.

**Comment by knuckolls** [comment]
Reviewed. Looks good to me. :+1:

**Pull request merged**
