### PR TITLE
Add support for networkName

### PR DESCRIPTION
**Pull request by wleese**
This is a bit limited at the moment, because we only need ipAddress{ networkName: "xx" }

Had to update go-marathon to get support for IPAddressPerTask

### CODE REVIEW

**Comment by DustinChaloupka** [comment]
Would it be possible to add a test for this? This project hasn't been well maintained or tested, but would like to improve upon that aspect. Just something that checks this new field in each of the two functions it was added to.

**Comment by wleese** [comment]
Sadly make test wants to pull some Banno internal stuff, so it's hard for me to perform any tests.

I've added 2 tests that seemed to make sense to me. I've also renamed networkname to network_name to be more consistent with other parameters.

**Comment by adamdecaf** [comment]
Does the vendor update conflict with [the vendor update we just did](https://github.com/Banno/terraform-provider-marathon/pull/44)?

**Comment by adamdecaf** [comment]
ok to test

**Comment by DustinChaloupka** [comment]
@adamdecaf That PR you linked did not update the `go-marathon` vendor, just terraform related vendors.

**Comment by adamdecaf** [comment]
Gah. It's hard to tell on github. 👍

**Comment by adamdecaf** [comment]
I'm going to release a version with the vendor update and then this merged.

**Comment by adamdecaf** [comment]
retest this please

**Pull request merged**
