### PR TITLE
Godeps

### PR DESCRIPTION
**Pull request by rubbish**
With the recent terraform 0.7 change which will require us to switch plugins, we need to set our terraform version this is built against to 0.6.15. I've godep save'd off what I had locally to build against.

### CODE REVIEW

**Comment by sherzberg** [comment]
👍

**Comment by adamdecaf** [comment]
👍

**Comment by DustinChaloupka** [comment]
👍

**Comment by rubbish** [comment]
I'm not sure the marathon tests work on our current version of docker on the jenkins slaves. 👎

**Pull request merged**
