### PR TITLE
This should fix our library for the upstream change.

### PR DESCRIPTION
**Pull request by daniellockard**

### CODE REVIEW

**Comment by daniellockard** [comment]
trigger this please

**Comment by daniellockard** [comment]
trigger this please

**Comment by daniellockard** [comment]
trigger this please

**Comment by daniellockard** [comment]
trigger this please

**Comment by daniellockard** [comment]
I can't get this to pass in jenkins, but it does locally. Please review @rubbish @sherzberg 


```bash
danny@MacBook-Pro ~/src/go/src/github.com/Banno/terraform-provider-marathon ±fix_for_upstream_pointer_change » ./test.sh
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccMarathonApp_basic
--- PASS: TestAccMarathonApp_basic (68.51s)
PASS
ok  	github.com/Banno/terraform-provider-marathon/marathon	68.519s
```

**Comment by rubbish** [comment]
Yeah, I think the mesos-agent images we have don't quite run right under the current docker version we have. :cry: 

:+1: Thanks @daniellockard

**Comment by rubbish** [comment]
Going to merge this in so stemcell can pick it up tomorrow morning.

**Pull request merged**
