### PR TITLE
godep save

### PR DESCRIPTION
**Pull request by rubbish**
I tried re-building this and found that I was missing dependency. So a I did a `godep restore` and then a `godep save`. All was good afterwards.

I verified that they're all there by cloning to a tmp `GOPATH` and doing a `go build`.

### CODE REVIEW

**Comment by DustinChaloupka** [comment]
👍

**Comment by sherzberg** [comment]
👍

**Comment by adamdecaf** [comment]
👍

**Comment by rubbish** [comment]
retest this please

**Comment by rubbish** [comment]
So I can't recreate what's happening in the jenkins build on my laptop. It might be something go 1.7 related which I have installed. I'll try in a jenkins slave image tomorrow.

**Comment by rubbish** [comment]
retest this please

**Pull request closed without merging**
