### PR TITLE
Update terraform vendor to 0.7.13

### PR DESCRIPTION
**Pull request by DustinChaloupka**
Updates the terraform vendor to 0.7.13.

### CODE REVIEW

**Comment by adamdecaf** [comment]
👍

**Comment by DustinChaloupka** [comment]
retest this please

**Comment by DustinChaloupka** [comment]
@adamdecaf I did the same sort of thing as the mesoskafka provider with this PR. It is a little different only because of the way marathon and mesos are interacting, but references to big are gone now.

The difference with this is that mesos agents do not actually run the marathon apps, it's just run on the local docker instance, so the marathon container needs access to the ports of the spun up apps. The easiest (only?) way I found was to use a network mode of `host` and specifying the mesos clusters as on the `localhost` host.

**Comment by adamdecaf** [comment]
Sweet! 👍

**Pull request merged**
