### PR TITLE
Updates deps for terraform 0.8.2

### PR DESCRIPTION
**Pull request by DustinChaloupka**
Updates deps for terraform 0.8.2. Should probably update the minor version for this once merged.

### CODE REVIEW

**Comment by mariomarin** [comment]
@adamdecaf Do you plan to merge this soon?

**Comment by adamdecaf** [comment]
@mariomarin Yea. We're a little behind on terraform versions. Do you need this released?

**Comment by DustinChaloupka** [comment]
I had gotten distracted by other things, I can get this up to date with the latest version and see about it being ready to merge.

**Comment by DustinChaloupka** [comment]
Closing in favor of #48

**Pull request closed without merging**
