### PR TITLE
upgrade go-marathon and added ignorehttp1xx to healthchecks

### PR DESCRIPTION
**Pull request by nicgrayson**
Note: I was not able to test this b/c the docker compose files pull from the banno internal docker registry.

### CODE REVIEW

**Comment by adamdecaf** [comment]
ok to test

**Comment by adamdecaf** [comment]
These tests passed for me. Do we need to make a call on `SetIgnoreHTTP1xx` though? 

Btw, We don't use this provider anymore. Any interest in maintaining it? The mesos/zk docker images only differ from official images by adding a CA for Banno. 

```
$ make test
go install .
docker pull python:3
3: Pulling from library/python
6d827a3ef358: Already exists
2726297beaf1: Already exists
7d27bd3d7fec: Already exists
44ae682c18a3: Already exists
824bd01a76a3: Pull complete
68fe59875298: Pull complete
9ca1d7ae0c4b: Pull complete
Digest: sha256:0a979dbff79f466aad8d92a89980ebe19cbd481b135d8cc9c0d843d8cf802ef9
Status: Downloaded newer image for python:3
docker-compose -f docker-compose.yml up -d
Creating terraformprovidermarathon_zookeeper_1
Creating terraformprovidermarathon_dns_1
Creating terraformprovidermarathon_mesos-agent2_1
Creating terraformprovidermarathon_mesos-agent1_1
Creating terraformprovidermarathon_mesos-master_1
Creating terraformprovidermarathon_marathon_1
sleep 10
TF_LOG=TRACE TF_LOG_PATH=./test-sh-tf.log TF_ACC=yes MARATHON_URL=http://dev.banno.com:8080 go test ./marathon -v
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccMarathonApp_basic
--- PASS: TestAccMarathonApp_basic (389.33s)
=== RUN   TestAccMarathonApp_ipAddress
--- PASS: TestAccMarathonApp_ipAddress (36.16s)
PASS
ok  	github.com/Banno/terraform-provider-marathon/marathon	425.504s
docker-compose -f docker-compose.yml kill
Killing terraformprovidermarathon_marathon_1 ... done
Killing terraformprovidermarathon_mesos-master_1 ... done
Killing terraformprovidermarathon_mesos-agent1_1 ... done
Killing terraformprovidermarathon_dns_1 ... done
Killing terraformprovidermarathon_zookeeper_1 ... done
docker-compose -f docker-compose.yml rm -f
Going to remove terraformprovidermarathon_marathon_1, terraformprovidermarathon_mesos-master_1, terraformprovidermarathon_mesos-agent1_1, terraformprovidermarathon_mesos-agent2_1, terraformprovidermarathon_dns_1, terraformprovidermarathon_zookeeper_1
Removing terraformprovidermarathon_marathon_1 ... done
Removing terraformprovidermarathon_mesos-master_1 ... done
Removing terraformprovidermarathon_mesos-agent1_1 ... done
Removing terraformprovidermarathon_mesos-agent2_1 ... done
Removing terraformprovidermarathon_dns_1 ... done
Removing terraformprovidermarathon_zookeeper_1 ... done
```

**Comment by nicgrayson** [comment]
@adamdecaf good point. fixed and amended. Also I'm okay with taking over the project if you want to transfer it.

**Comment by adamdecaf** [comment]
@nicgrayson Sure thing. Do you want it transferred to your account or an org?

**Comment by nicgrayson** [comment]
@adamdecaf me. Org doesn't have a public github.com presence.

**Comment by adamdecaf** [comment]
@nicgrayson Sure thing. Can you delete your fork? Github won't let me transfer this repo.

**Comment by nicgrayson** [comment]
@adamdecaf can you merge first so i don't lose this branch?

**Pull request merged**
